<?php

namespace IndexBundle\Entity;

use IndexBundle\Entity\Post;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLatest($limit = Post::NUM_ITEMS)
	{
		return $this->createQueryBuilder('p')
			->select('p')
			->where('p.publishedAt <= :now')->setParameter('now', new \DateTime())
			->orderBy('p.publishedAt', 'desc')
			->setMaxResults($limit)
			->getQuery()
			->getResult()
			;
	}
}
